Repository YABHAKRITI-Robotics-Club/CodeToGrow, pull requests merged in 2020-10, with the labels that each got.

#4 Addaded Readme(Hactoberfest version)
  README.md
Labels: hacktoberfest-accepted

#6 addaded tower of honoi
  README.md
  Recursion and Back Tracking/Level-1/Recursion-Basics/Tower-Of-Honoi/Question.md
  Recursion and Back Tracking/Level-1/Recursion-Basics/Tower-Of-Honoi/towerOfHonoi.java
Labels: hacktoberfest-accepted

#8 Added Interview Questions
  Interview Questions/Initial.md
Labels: hacktoberfest-accepted

#9 Added Program to find Inorder Predecessor and Successor in binary tree
  Trees/Binary Search Tree/Inorder Predecessor and Successor.py
Labels: hacktoberfest-accepted

#10 Added Code For removing elements lying in the specific range in BST
  Trees/Binary Search Tree/Inorder Traversal.py
  Trees/Binary Search Tree/Merge Two BSTs.py
  Trees/Binary Search Tree/Remove Nodes In Given Range In BST.py
Labels: hacktoberfest-accepted

#11 Created Q1.cpp
  Basic of Programming/Arrays/Q1,cpp
Labels: hacktoberfest-accepted

#12 Created Q2.cpp
  Basic of Programming/Arrays/Q2.cpp
Labels: hacktoberfest-accepted

#13 Created Q1.cpp
  Basic of Programming/Patterns/Q1.cpp
Labels: hacktoberfest-accepted

#14 Created Q1.cpp
  Basic of Programming/Patterns/Q1.cpp
Labels: hacktoberfest-accepted

#15 Added Code for morrise traversal in BST
  Trees/Binary Search Tree/Find Kth smallest element in BST Using Morrise Traversal.py
Labels: hacktoberfest-accepted

#17 Created Questions for Linked List
  .DS_Store
  Advance Data Structure/.DS_Store
  Advance Data Structure/Suffix-Tree/.DS_Store
  Linked Lists/.DS_Store
  Linked Lists/ReverseLinkedList.c++
  Linked Lists/findCycle.c++
  Linked Lists/linked list
  Linked Lists/middleElement.c++
  Linked Lists/singlyLinkedList.c++
Labels: hacktoberfest-accepted

#18 Added_new_file_to_dynamic_programming
  .DS_Store
  Dynamic Programming/.DS_Store
  Dynamic Programming/Level-2/ Longest_palindromic_substring/ Question 
  Dynamic Programming/Level-2/ Longest_palindromic_substring/ Solution
  Dynamic Programming/Level-2/ Longest_palindromic_substring/.DS_Store
Labels: hacktoberfest-accepted

#20 Question and readme updated
  Basic of Programming/Matrix/2D-Arrays/Matrix-Multiplication/Question.md
  Basic of Programming/Matrix/2D-Arrays/Matrix-Multiplication/matrixMultiplication.java
  Cheet-Sheets/STL Quick Reference.pdf
  README.md
Labels: documentation, hacktoberfest-accepted

#19 anagram_question(easy)
  Stacks & Queue/Stock Span (Imp)/Question.md
  Stacks & Queue/Stock Span (Imp)/Solution.cpp
  String Algorithms/Group Anagrams Together/Question.md
  String Algorithms/Group Anagrams Together/Solution.cpp
Labels: hacktoberfest-accepted, hactoberfest

#23 Solution.cpp
  Stacks & Queue/Parenthesis Checker/Solution
Labels: hacktoberfest-accepted, hactoberfest

#28 Added shortest path problem related to graph.
  Basics+1/Sorting/README.md
  Graphs/C++/graph.hpp
  Graphs/C++/shortest_path.hpp
  Graphs/C++/test.cpp
  Graphs/Initial.md
  Graphs/README.md
Labels: hacktoberfest-accepted, hactoberfest

#29 questions Added
  Basic of Programming/Arrays/Initial.md
  Basic of Programming/Arrays/QuestionList.md
  Recursion and Back Tracking/Level-1/Recursion In Arraylist/Vector/GetSubSequence/Question.md
  Recursion and Back Tracking/Level-1/Recursion In Arraylist/Vector/KeyPadCombonation/Question.md
  Recursion and Back Tracking/Level-1/Recursion In Arraylist/Vector/MazePaths/Question.md
  Recursion and Back Tracking/Level-1/Recursion In Arraylist/Vector/MazePathsJumps/Question.md
  Recursion and Back Tracking/Level-1/Recursion-a-level-up/PrintKeyPadCombination/Question.md
  Recursion and Back Tracking/Level-1/Recursion-a-level-up/PrintMazePathsWidJumps/Question.md
  Recursion and Back Tracking/Level-1/Recursion-a-level-up/PrintPermutations/Question.md
  Recursion and Back Tracking/Level-1/Recursion-a-level-up/PrintSubSequence/Question.md
  Recursion and Back Tracking/Level-1/Recursion-a-level-up/printMazePaths/Question.md
Labels: hacktoberfest-accepted

#33 Solution.cpp
  Stacks & Queue/Previous Greater Element/Solution.cpp
Labels: hacktoberfest-accepted

#35 Added files to BT
  Trees/Binary Tree/symmetric tree/problem.md
  Trees/Binary Tree/symmetric tree/solution.cpp
Labels: hacktoberfest-accepted

#36 Added files to BT
  Trees/Binary Tree/Binary Tree Zigzag Level Order Traversal/problem.md
  Trees/Binary Tree/Binary Tree Zigzag Level Order Traversal/solution.cpp
Labels: hacktoberfest-accepted

#37 Added files to BT
  Trees/Binary Tree/invert the Binary Tree/problem.md
  Trees/Binary Tree/invert the Binary Tree/solution.cpp
Labels: hacktoberfest-accepted

#39 Added Code For Deleting A Given Node In BST
  Trees/Binary Search Tree/Delete A Given Node In BST.py
Labels: hacktoberfest-accepted

#41 Added Code To Find The Lowest Common Ancestor In BST
  Trees/Binary Search Tree/Find Lowest Common Ancestor in BST.py
Labels: hacktoberfest-accepted

#42 Added Code For Find The Intersection Of Two Nodes
  Trees/Binary Search Tree/Convert A Binary Tree Into BST.py
  Trees/Binary Search Tree/Convert A Binary Tree Into BST/Convert A Binary Tree Into BST.py
  Trees/Binary Search Tree/Delete A Given Node In BST.py
  Trees/Binary Search Tree/Delete A Given Node In BST/Delete A Given Node In BST.py
  Trees/Binary Search Tree/Find Intersection Of Two BSTs/Find Interection Of Two BST.py
  Trees/Binary Search Tree/Find Kth smallest element in BST Using Morrise Traversal/Find Kth smallest element in BST Using Morrise Traversal.py
  Trees/Binary Search Tree/Find Lowest Common Ancestor in BST.py
  Trees/Binary Search Tree/Find Lowest Common Ancestor in BST/Find Lowest Common Ancestor in BST.py
  Trees/Binary Search Tree/Inorder Predecessor and Successor/Inorder Predecessor and Successor.py
  Trees/Binary Search Tree/Inorder Traversal/Inorder Traversal.py
  Trees/Binary Search Tree/Merge Two BSTs/Merge Two BSTs.py
  Trees/Binary Search Tree/Remove Nodes In Given Range BST/Remove Nodes In Given Range In BST.py
Labels: hacktoberfest-accepted

#43 Added java solution for Q4 of basics of programming->arrays
  Basic of Programming/Arrays/Q4 Sort the array/Sol.java
Labels: hacktoberfest-accepted

#44 Add move negative numbers to beginning of array
  Basic of Programming/Arrays/Q5. Move negative numbers to begining of array/Problem statement.txt
  Basic of Programming/Arrays/Q5. Move negative numbers to begining of array/Solution.cpp
Labels: hacktoberfest-accepted

#45 Added python solution for Q4 of basics of programming->arrays
  Basic of Programming/Arrays/Q4 Sort the array/solution.py
Labels: hacktoberfest-accepted

#46 Added python solution for Q7 of basics of programming->arrays cyclic …
  Basic of Programming/Arrays/Q7 Cyclic rotation/sol.py
Labels: hacktoberfest-accepted

#47 Create max_in_array.cpp
  Recursion and Back Tracking/Level-1/Recursion In Array/maxInArray/max_in_array.cpp
Labels: hacktoberfest-accepted

#48 Create tower_of_hanoi.cpp
  Recursion and Back Tracking/Level-1/Recursion-Basics/Tower-Of-Honoi/tower_of_hanoi.cpp
Labels: hacktoberfest-accepted

#49 heap sort added
  Basics+1/Sorting/C++/insertion.cpp
  Basics+1/Sorting/heap_sort.cpp
  Trees/B+ Tree/insertion.cpp
Labels: hacktoberfest-accepted

#50 merge sort added
  Basics+1/Sorting/C++/merge_sort.cpp
Labels: hacktoberfest-accepted

#51 Added python solutions for Recursion In Array
  Recursion and Back Tracking/Level-1/Recursion In Array/allIndices/allindices.py
  Recursion and Back Tracking/Level-1/Recursion In Array/maxInArray/maxInArray.py
Labels: hacktoberfest-accepted

#52 Added python solutions for Recursion basics
  Recursion and Back Tracking/Level-1/Recursion-Basics/Tower-Of-Honoi/tower_of_hanoi.py
  Recursion and Back Tracking/Level-1/Recursion-Basics/printZigzag/printZigZag.py
Labels: hacktoberfest-accepted

#53 Added python solution for Backtracking
  Recursion and Back Tracking/Level-1/Recursion-BackTracking/rat_in_a_maze.py
Labels: hacktoberfest-accepted

#54 Added python solution for Recursion-a-level-up
  Recursion and Back Tracking/Level-1/Recursion-a-level-up/PrintKeyPadCombination/print_keypad.py
  Recursion and Back Tracking/Level-1/Recursion-a-level-up/PrintMazePathsWidJumps/print_maze_paths_jumps.py
  Recursion and Back Tracking/Level-1/Recursion-a-level-up/PrintPermutations/print_permutations.py
  Recursion and Back Tracking/Level-1/Recursion-a-level-up/PrintSubSequence/print_subsequence.py
  Recursion and Back Tracking/Level-1/Recursion-a-level-up/printMazePaths/print_maze_paths.py
Labels: hacktoberfest-accepted
